---
title: "04_PT1475_Epithelial_Cell_Characterization"
author: "Aylin Henstridge (Aylinhen@umich.edu)"
date: "2026-02-11"
output: 
  html_document:
    toc: true
    toc_depth: 2
    warnings: FALSE
    number_sections: true
    toc_float: true
    code_download: true
    fig_caption: true
    fig_width: 10
    fig_height: 6
    highlight: 'tango'
    theme: united
knit: (function(input, ...){rmarkdown::render(input, output_dir = "../DOCUMENTS")})
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(toc = TRUE)
```

```{css, echo = FALSE}
pre {
  max-height: 500px;
  overflow-y: auto;
}

pre[class]{
  max-height: 500px;
}

.scroll-100{
  max-height: 500px;
  overflow-y: auto;
  background-color: inherit;
}
```

# Characterize Epithelial Cells

```{r, warning=FALSE, message=FALSE}
# Verify the paths
library(Seurat)
library(SeuratObject)
library(SeuratWrappers)
library(AUCell)
library(monocle3)
library(GSVA)
library(pheatmap)
library(tidyverse)
library(RColorBrewer)
library(readxl)
library(DT)
library(EnhancedVolcano)
library(enrichplot)
library(cowplot)
library(DESeq2)
library(ggalt)
library(devtools)
library(ashr)
library(tidytree)
library(dplyr)
library(fgsea)
library(msigdbr)

#source object
pt1475 <- readRDS("../OBJECTS/1475_merged_CORRECTED.rds")
```

```{r, message=FALSE, warning=FALSE}
Idents(pt1475) <- "timepoint"
levels(pt1475)

T1_3 <- subset(pt1475, idents = c("1", "3"))
```

```{r, message=FALSE, warning=FALSE}
Idents(T1_3) <- "Level1Labels_Merged"
levels(T1_3)
epi_1_3 <- subset(T1_3, idents = "Epi")

DimPlot(epi_1_3, split.by = "timepoint")

epi_1_3 <- NormalizeData(epi_1_3, normalization.method = "LogNormalize", scale.factor = 10000)
epi_1_3 <- FindVariableFeatures(epi_1_3, selection.method = "vst", nfeatures = 2000, assay = "CorrectedCounts")
epi_1_3 <- ScaleData(epi_1_3, features = rownames(epi_1_3),verbose = FALSE)

#---------------------------------------------------------------------
Idents(epi_1_3) <- 'timepoint'
DimPlot(epi_1_3)

levels(epi_1_3)

patient1475.markers <- FindMarkers(epi_1_3, ident.1 = "1", ident.2 = "3", assay = "RNA", test.use = "MAST", verbose = FALSE, recorrect_umi = FALSE, logfc.threshold = 0)
write.csv(patient1475.markers, file = "../DATA/1475_epi_patient_DE.csv")
```

# Make heatmap of DE genes
```{r, message=FALSE, warning=FALSE}
DE_LIST <- c("BDNF-AS", "TGFB2", "RERG", "OMG", "MMP3","MMP12", "SOX6","IL7", "PAX8","CNTN3","RELCH","NEO1","VCAM1", "DAB1","PLA2R1","PSMA3","NRG3", "NFKBIA", "IER3", "VEGFB", "MAPK3","IL32", "IFI27L2", "IFITM2", "GAS5", "MIF", "KRT18","KRT10", "GAPDH", "ALDOA", "PGAM1", "TPI1", "TXN", "PRDX1", "PRDX2", "PLIN3", "RBX1")
DE2 <- c("TGFB2", "RERG", "OMG", "MMP3", "MMP12","NTN1", "NEO1", "NRP1", "SEMA4G", "IL7",'NRG3', "ADAM10", "LRP6", "ROR1", "RYK", "FZD5", "LRP5", "CTNNB1", "NFKBIA", "VEGFB", "MAPK3", "IL32", "IFITM2", "MIF", "KRT18", "GAPDH", "ALDOA", "GAS5")
DoHeatmap(epi_1_3, features = DE2) + scale_fill_gradientn(colors = rev(RColorBrewer::brewer.pal(n = 10, name = "RdYlBu")))

#DE4 <- c( "LRP6", "ROR1", "RYK", "FZD5", "LRP5", "AXIN2", "AXIN1", "CTNNB1", "PTCH1", "GLI1", "GLI2")
#DoHeatmap(epi_1_3, features = DE4) + scale_fill_gradientn(colors = rev(RColorBrewer::brewer.pal(n = 10, name = "RdYlBu")))


```