---
title: "04_PT1475_Epithelial_Cell_Characterization"
author: "Aylin Henstridge (Aylinhen@umich.edu)"
date: "2025-12-09"
output: 
  html_document:
    toc: true
    toc_depth: 2
    warnings: FALSE
    number_sections: true
    toc_float: true
    code_download: true
    fig_caption: true
    fig_width: 10
    fig_height: 6
    highlight: 'tango'
    theme: united
knit: (function(input, ...){rmarkdown::render(input, output_dir = "../DOCUMENTS")})
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(toc = TRUE)
```

```{css, echo = FALSE}
pre {
  max-height: 500px;
  overflow-y: auto;
}

pre[class]{
  max-height: 500px;
}

.scroll-100{
  max-height: 500px;
  overflow-y: auto;
  background-color: inherit;
}
```

# Introduction - Load Packages and Libraries 
```{r, warning=FALSE, message=FALSE}
# Verify the paths
suppressPackageStartupMessages({
library(Seurat)
library(SeuratObject)
library(SeuratWrappers)
library(AUCell)
library(monocle3)
library(GSVA)
library(pheatmap)
library(tidyverse)
library(RColorBrewer)
library(readxl)
library(DT)
library(EnhancedVolcano)
library(enrichplot)
library(cowplot)
library(DESeq2)
library(ggalt)
library(devtools)
library(ashr)
library(tidytree)
library(dplyr)
library(fgsea)
library(msigdbr)
})

#source object
pt1475 <- readRDS("../OBJECTS/Patient_1475/1475_merged_CORRECTED.rds")
DimPlot(pt1475, split.by = "time_point")
Idents(pt1475) <- "time_point"

T1_3 <- subset(pt1475, idents = c("1", "3"))

Idents(T1_3) <- "Level1Labels"
epi_1_3 <- subset(T1_3, idents = "Epi")

DimPlot(epi_1_3, split.by = "time_point")

epi_1_3 <- NormalizeData(epi_1_3, normalization.method = "LogNormalize", scale.factor = 10000)
epi_1_3 <- FindVariableFeatures(epi_1_3, selection.method = "vst", nfeatures = 2000, assay = "CorrectedCounts")
epi_1_3 <- ScaleData(epi_1_3, features = rownames(epi_1_3),verbose = FALSE)
```

# Differential Expresion of Epithelial Cells between Treatment Naive and Recurrence 
```{r, warning=FALSE, message=FALSE}
#---------------------------------------------------------------------
Idents(epi_1_3) <- 'time_point'
DimPlot(epi_1_3)

levels(epi_1_3)

patient1475.markers <- FindMarkers(epi_1_3, ident.1 = "1", ident.2 = "3", assay = "RNA", test.use = "MAST", verbose = FALSE, recorrect_umi = FALSE, logfc.threshold = 0)
patient1475.markers.reversed <- FindMarkers(epi_1_3, ident.1 = "3", ident.2 = "1", assay = "RNA", test.use = "MAST", verbose = FALSE, recorrect_umi = FALSE, logfc.threshold = 0)

write.csv(patient1475.markers, file = "../DATA_FILES/1475_epi_patient_DE.csv")
```

## Plot differentially expressed genes
```{r}
DE_LIST <- c("BDNF-AS", "TGFB2", "RERG", "OMG", "MMP3","MMP12", "SOX6","IL7", "PAX8","CNTN3","RELCH","NEO1","VCAM1", "DAB1","PLA2R1","PSMA3","NRG3", "NFKBIA", "IER3", "VEGFB", "MAPK3","IL32", "IFI27L2", "IFITM2", "GAS5", "MIF", "KRT18","KRT10", "GAPDH", "ALDOA", "PGAM1", "TPI1", "TXN", "PRDX1", "PRDX2", "PLIN3", "RBX1")
DE2 <- c("TGFB2", "RERG", "OMG", "MMP3", "MMP12","NTN1", "NEO1", "NRP1", "SEMA4G", "IL7",'NRG3', "ADAM10", "LRP6", "ROR1", "RYK", "FZD5", "LRP5", "CTNNB1", "NFKBIA", "VEGFB", "MAPK3", "IL32", "IFITM2", "MIF", "KRT18", "GAPDH", "ALDOA", "GAS5")
DoHeatmap(epi_1_3, features = DE2) + scale_fill_gradientn(colors = rev(RColorBrewer::brewer.pal(n = 10, name = "RdYlBu")))

#DE4 <- c( "LRP6", "ROR1", "RYK", "FZD5", "LRP5", "AXIN2", "AXIN1", "CTNNB1", "PTCH1", "GLI1", "GLI2")
#DoHeatmap(epi_1_3, features = DE4) + scale_fill_gradientn(colors = rev(RColorBrewer::brewer.pal(n = 10, name = "RdYlBu")))


##########################################################################################################################################################################################
```

# Gene Set Enrichment and Pathway Analysis

## GSEA
```{r, warning=FALSE, message=FALSE}
library(GSVA)
library(fgsea)

#source functions
source("../UTILS/pseudobulk_functions.R")
source("../UTILS/patient_split.R")
source("../UTILS/GSEA.R")

library(msigdbr)
hallmarks_pathways <- msigdbr(species = "Homo sapiens", category = 'H', subcategory = NULL)
hallmarks_pathways <- split(x = hallmarks_pathways$gene_symbol, f = hallmarks_pathways$gs_name)
#this code takes the hallmark pathway and splits it into vectors with each pathway and the genes that belong to each pathway

#loaded hall mark pathway gene expression and made an expression df using the information from the RNA assay
Idents(object = epi_1_3) <- "time_point"
patient1475.markers$gene <- rownames(patient1475.markers)
DEG_patient <- patient1475.markers %>% arrange(desc(avg_log2FC))
fold_changes <- DEG_patient$avg_log2FC
names(fold_changes) <- DEG_patient$gene
head(fold_changes)


#loaded hall mark pathway gene expression and made an expression df using the information from the RNA assay
#reverse DE to validate accuracy 
patient1475.markers.reversed$gene <- rownames(patient1475.markers.reversed)
DEG_patient <- patient1475.markers.reversed %>% arrange(desc(avg_log2FC))
fold_changes2 <- DEG_patient$avg_log2FC
names(fold_changes2) <- DEG_patient$gene
head(fold_changes2)


gsea_patient <- fgsea(hallmarks_pathways, stats = fold_changes, nperm = 1000)
gsea_sig <- gsea_patient %>% filter(padj < 0.5)

gsea_tidy <- gsea_patient %>% as_tibble() %>% arrange(desc(NES))
gsea_sig_tidy <- gsea_tidy %>% filter(padj < 0.5)

ggplot(gsea_sig,
       aes(reorder(pathway, NES), NES)) +
  geom_col(aes(fill = padj)) +
  coord_flip() +
  labs(x = "Pathway", y = "Normalized Enrichment Score", title = "Hallmark Pathways NES from GSEA")+
  theme_minimal()
```

## GO Genes
```{r, warning=FALSE, message=FALSE}
##########################################################################################################################################################
#GO Genes
library(clusterProfiler)
library(enrichplot)
library(pathview)

# we want the log2 fold change 
Go_logfoldchange <- patient1475.markers$avg_log2FC
# name the vector
names(Go_logfoldchange) <- patient1475.markers$gene

# omit any NA values 
Go_logfoldchange_short<-na.omit(Go_logfoldchange)

# sort the list in decreasing order (required for clusterProfiler)
Go_logfoldchange_short = sort(Go_logfoldchange_short, decreasing = TRUE)
library("org.Hs.eg.db", character.only = TRUE)
gse <- gseGO(geneList = Go_logfoldchange_short, 
             ont ="ALL", 
             keyType = "SYMBOL",
             nPerm = 10000, 
             minGSSize = 3, 
             maxGSSize = 800, 
             pvalueCutoff = 0.07, 
             verbose = TRUE, 
             OrgDb = org.Hs.eg.db, 
             pAdjustMethod = "fdr")
require(DOSE)
dotplot(gse, showCategory=10, split=".sign") + facet_grid(.~.sign)
```

## KEGG 
```{r, warning=FALSE, message=FALSE}
##############################################################################################################
#KEGG Reactome
library(clusterProfiler)
library(org.Hs.eg.db)

up_in_t1 <- patient1475.markers.reversed %>%
  filter(avg_log2FC > 0 )

down_in_t1 <- patient1475.markers.reversed %>%
  filter(avg_log2FC < 0)

up_ids <- bitr(up_in_t1$gene, fromType="SYMBOL", toType="ENTREZID", OrgDb=org.Hs.eg.db)
down_ids <- bitr(down_in_t1$gene, fromType="SYMBOL", toType="ENTREZID", OrgDb=org.Hs.eg.db)

up_kegg <- enrichKEGG(gene=up_ids$ENTREZID, organism="hsa", pvalueCutoff=0.05)
down_kegg <- enrichKEGG(gene=down_ids$ENTREZID, organism="hsa", pvalueCutoff=0.05)

up_df <- as.data.frame(up_kegg)
down_df <- as.data.frame(down_kegg)

up_df$direction <- "Down in T1"
down_df$direction <- "Up in T1"

up_df$enrichment_score <- -log10(up_df$p.adjust)
down_df$enrichment_score <- log10(down_df$p.adjust)

combined_df <- bind_rows(up_df, down_df) %>%
  filter(!is.infinite(enrichment_score)) %>%
  arrange(desc(abs(enrichment_score))) %>%
  slice(1:50)  # adjust number of categories shown

# Plot
ggplot(combined_df, aes(x = reorder(Description, enrichment_score), y = enrichment_score, fill = direction)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  scale_fill_manual(values = c("Up in T1" = "red", "Down in T1" = "blue")) +
  labs(title = "KEGG Pathways Enriched in T3",
       x = "Pathway", y = "Signed -log10(adjusted p-value)") +
  theme_minimal(base_size = 14)

#To see each set of pathways on seperate bar plots, i.e whats up v. down 
#barplot(up_kegg, showCategory=20, title="Pathways UP in T1")
#barplot(down_kegg, showCategory=20, title="Pathways DOWN in T1")

### REACTOME
#library(ReactomePA)

#reactome_enrich <- enrichPathway(gene = gene_df$ENTREZID,
                                 #organism = "human",
                                 #pvalueCutoff = 0.03,
                                 #readable = TRUE)

#barplot(reactome_enrich, showCategory = 20)
```

## CNET Plot
```{r, warning=FALSE, message=FALSE}
#No significant hits of interest were found in reactome geneset. 
### CNET PLOTS 
selected_pathways <- c("Focal adhesion", "Axon guidance", "MAPK signaling pathway")

all_ids <- bitr(patient1475.markers.reversed$gene,
                fromType="SYMBOL", toType="ENTREZID", OrgDb=org.Hs.eg.db)

all_kegg <- enrichKEGG(gene = all_ids$ENTREZID,
                       organism = "hsa",
                       pvalueCutoff = 0.05)
logfc_vector <- patient1475.markers.reversed$avg_log2FC

all_kegg <- setReadable(all_kegg, OrgDb = org.Hs.eg.db, keyType = "ENTREZID")

# You can use `showCategory = 5` or specify pathways by name
cnetplot(all_kegg,
         showCategory = selected_pathways,
         circular = FALSE,
         color.params = list(foldChange = logfc_vector, edge = TRUE)) +
  ggtitle("CNET Plot of Top KEGG Pathways") +
  scale_color_gradientn(colors = c("blue", "white", "red"),
                        values = scales::rescale(c(min(logfc_vector), 0, max(logfc_vector)))) +
  ggraph::geom_node_text(aes(label = name), repel = TRUE, size = 3, max.overlaps = Inf)
```
# Differentially Expressed Genes Heatmap Plot
```{r, warning=FALSE, message=FALSE}
DE2 <- c("TGFB2", "RERG", "OMG", "MMP3", "MMP12","NTN1","NTN4","NLK", "MAPK10", "NGEF" ,"NEO1", "NRP1", "SEMA4G", "IL7",'PARD3', 'NRG3', "ADAM10", "NFKBIA", "VEGFB", "MAPK3", "IL32", "IFITM2", "MIF", "KRT18", "GAPDH", "ALDOA", "GAS5")
#CNET <- c("SHH", "PLXNB2","NGEF", "NTN4", "RGS3","CXCL12", "SEMA4G", "SEMA3E", "EPHA2", "SMEA4A", "ILK", "PAK6", "SEMA4F", "SHH", "PARD3")
#CNET2 <- c("BDNF", "FGF18", "EPOR","COL6A3", "IL4R", "MYC", "BCL2", "SOS2")
#CNET3 <- c("WNT2", "MAPK10", "FRAT2", "PRICKLE4", "NLK", "TP53")
DoHeatmap(epi_1_3, features = DE2) + scale_fill_gradientn(colors = rev(RColorBrewer::brewer.pal(n = 10, name = "RdYlBu")))
```
