---
title: "06_Myeloid_Cell_Characterization"
author: "Aylin Henstridge (Aylinhen@umich.edu)"
date: "2026-02-11"
output: 
  html_document:
    toc: true
    toc_depth: 2
    warnings: FALSE
    number_sections: true
    toc_float: true
    code_download: true
    fig_caption: true
    fig_width: 10
    fig_height: 6
    highlight: 'tango'
    theme: united
knit: (function(input, ...){rmarkdown::render(input, output_dir = "../DOCUMENTS")})
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(toc = TRUE)
```

```{css, echo = FALSE}
pre {
  max-height: 500px;
  overflow-y: auto;
}

pre[class]{
  max-height: 500px;
}

.scroll-100{
  max-height: 500px;
  overflow-y: auto;
  background-color: inherit;
}
```

# Load in libraries and data
```{r, message=FALSE, warning=FALSE}
#Myeloid Cells 
library(Seurat)
library(monocle3) 
library(pheatmap)
library(tidyverse)
library(RColorBrewer)
library(readxl)
library(DT)
library(fgsea)
library(msigdbr)
library(EnhancedVolcano)
library(enrichplot)
library(cowplot)
library(DESeq2)
library(ggalt)
library(devtools)
library(ashr)
library(tidytree)
library(clusterProfiler)
`%nin%` <- Negate(`%in%`)
getPalette <- colorRampPalette(brewer.pal(9, 'Set1'))
source("../UTILS/pseudobulk_functions.R")

##############################################
#Myeloid subset
Myeloid<- readRDS("../OBJECTS//Myeloid_subset.rds")
```

```{r, message=FALSE, warning=FALSE}
DimPlot(object =Myeloid, reduction = "umap", pt.size = 0.1, label = F, repel = T, cols = getPalette(length(levels(Myeloid))), split.by= "timepoint")
```

```{r, message=FALSE, warning=FALSE}
DefaultAssay(Myeloid) <- "integrated"
# dimension reduction and clustering of integrated object
Myeloid <- RunPCA(Myeloid, verbose = FALSE)
ElbowPlot(Myeloid, 50)
Myeloid <- RunUMAP(Myeloid, reduction = "pca", dims = 1:25, verbose = FALSE)
Myeloid <- FindNeighbors(Myeloid, reduction = "pca", dims = 1:25)
Myeloid <- FindClusters(Myeloid, resolution = 1.8)
Myeloid[["Myeloid_seurat_clusters"]] <- Idents(object = Myeloid)

DimPlot(object =Myeloid, reduction = "umap", pt.size = 0.1, label = T, repel = T, cols = getPalette(length(levels(Myeloid))))
```

# Subcluster Myeloid Cells
## FeaturePlots
We use this to look at gene expression.
```{r, message=FALSE, warning=FALSE}
DefaultAssay(Myeloid) <- "SCT"
FeaturePlot(object = Myeloid, features = c("S100A8", "S100A9", "G0S2", "FCGR3B", "HLA-DRA"), cols = c("grey", "red"), reduction = "umap", pt.size = .5) #neutrophil markers
FeaturePlot(object = Myeloid, features = c("CCR2", "MARCO", "APOE","CD14", "HLA-DRA", "CD68", "FCGR3B", "FCGR3A", "LYZ", "CCR7"), cols = c("grey", "red"), reduction = "umap", pt.size = .5, order = T)
FeaturePlot(object = Myeloid, features = c("PTPRC", "CD14", "ITGAM", "ITGAX", "APOE", "C1QA", "CEACAM8", "FUT4", "HLA-DQA1"), cols = c("grey", "red"), reduction = "umap", pt.size = .5) #Myeloid
FeaturePlot(object = Myeloid, features = c("FCGR3B","S100A8",  "CCR2","LYZ", "CD14","C1QA",   "FCGR3A", "LILRA5", "MARCO", "APOE", "HLA-DRA","CLEC9A"), cols = c("grey", "red"), reduction = "umap", pt.size = .5, order = T) #Myeloid
FeaturePlot(object = Myeloid, features = c('APOE', 'MARCO'), cols = c("grey", "red"), reduction = "umap", pt.size = .5) #Myeloid
FeaturePlot(object = Myeloid, features = c('IFIT3'), cols = c("grey", "red"), reduction = "umap", pt.size = .5) #Myeloid
```

## Dot Plot
```{r, message=FALSE, warning=FALSE}
DotPlot(object = Myeloid, features = c("FCGR3B","S100A8", "FCN1", "CCR2","LYZ", "CD14","C1QA",   "FCGR3A", "LILRA5", "MARCO", "APOE", "HLA-DRA","CLEC9A", "FCER1A", 'LAMP3'), cols = c("white", "magenta4")) +theme(legend.position = "right",
                                                                                                                                                                                                                    axis.text.x = element_text(angle = 45, size = 10,  hjust = 1))
```

```{r, message=FALSE, warning=FALSE, eval=FALSE}
Myeloid <- PrepSCTFindMarkers(Myeloid, assay = "SCT", verbose = TRUE)
markers <- FindAllMarkers(Myeloid, assay = 'SCT', min.pct = 0.25, only.pos = T)
```

## Name the clusters level 1
```{r, message=FALSE, warning=FALSE}
Idents(object = Myeloid) <- 'Myeloid_seurat_clusters'
levels(Myeloid)
current.cluster.ids <- c(0,1,2,3,4,5,6,7,8,9,10,11,12,13,14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25)
DimPlot(Myeloid, pt.size = 0.05, label = T)
new.cluster.ids <- c('Granulocyte', 'Granulocyte', 'Granulocyte', 'Granulocyte', 'Granulocyte', 'Classical Macrophage', 
                     'Activated Granulocyte', 'Granulocyte', 'Alternatively Activated Macrophage', 'Classical Macrophage', 'Classical Macrophage',
                     'Granulocyte', 'Activated Granulocyte', 'Granulocyte', 'Granulocyte', 'Nonclassical Macrophage', 
                     'Granulocyte', 'Classical Macrophage', 'Classical Macrophage', 'Alternatively Activated Macrophage', 'Classical Macrophage', 
                     'Granulocyte', 'Alternatively Activated Macrophage', 'Dendritic', 'Dendritic', 'Activated Granulocyte')
names(x = new.cluster.ids) <- levels(x = Myeloid)
Myeloid<- RenameIdents(object = Myeloid, new.cluster.ids)

Myeloid[["Level1Labels_Myeloid"]] <- Idents(object = Myeloid)

Idents(object=Myeloid) <- 'Level1Labels_Myeloid'
Idents(Myeloid) <- factor(Idents(Myeloid), levels = rev(c('Granulocyte', "Activated Granulocyte", 'Classical Macrophage', 'Nonclassical Macrophage', 'Alternatively Activated Macrophage', 'Dendritic')))
levels(Myeloid)
DefaultAssay(Myeloid) <- "SCT"
```

```{r, message=FALSE, warning=FALSE}
DotPlot(object = Myeloid, features = c("FCGR3B","S100A8", 'IFIT1', 'IFIT3', "HLA-DRA","FCN1", "LYZ",  "FCGR3A", "LILRA5", "CD14","C1QA",  "APOE","SPP1", "FCER1A", "BATF3", "CLEC9A"), cols = c("white", "magenta4")) +theme(legend.position = "right",
                                                                                                                                                                                                                                 axis.text.x = element_text(angle = 45, size = 10,  hjust = 1))
DimPlot(object =Myeloid, reduction = "umap", pt.size = 0.1, label = F, repel = T, split.by= "timepoint")

DimPlot(object =Myeloid, reduction = "umap", pt.size = 0.1, label = F, repel = T, cols = c( 
  "Classical Macrophage" = "coral1",
  "Dendritic" = "lightskyblue1",
  "Granulocyte" = "violetred",
  "Activated Granulocyte" = "thistle", 
  "Nonclassical Macrophage" = "peachpuff", 
  "Alternatively Activated Macrophage" = "yellow"))
```

```{r, message=FALSE, warning=FALSE, eval=FALSE}
saveRDS(Myeloid, "../OBJECTS/Annotated_Longitudinal_Myeloid_AH.rds")
```

# Let's make some histograms

```{r, message=FALSE, warning=FALSE}
#Now let's do a histogram by patient and time point
Myeloid$Level1Labels_Myeloid<- droplevels(Myeloid@meta.data$Level1Labels_Myeloid)
#splitting samples
samples.list <- unique(Myeloid$sample_id)
clusters <- lapply(samples.list, function(x){
  subset <- subset(Myeloid, subset = sample_id == x)
  dist <- data.frame(table(subset$Level1Labels_Myeloid))
  
  return(dist)
})

names(clusters) <- samples.list

#calculate relative freq (fractions) of each cell type
clusters_percent <- lapply(clusters, FUN = function(x){
  summ <- sum(x$Freq)
  x$Freq <- (x$Freq/summ)
  return(x)
})

#making things ggplot-friendly!
clusters_dist <- reshape2::melt(clusters, id.var = "Var1")
colnames(clusters_dist) <- c("Level1Labels_Myeloid","variable","value","sample_id")   
clusters_percent_dist <- reshape2::melt(clusters_percent, id.var = "Var1")
colnames(clusters_percent_dist) <- c("Level1Labels_Myeloid","variable","value","sample_id")

ggplot(clusters_percent_dist, aes(fill=Level1Labels_Myeloid, y = value, x = sample_id)) + 
  scale_x_discrete(limits = c('1402_T1', '1402_T2', '1550_T1', '1550_T2', '1471_T1', '1471_T2', '1475_T1', '1475_T2', '1529_T1', '1529_T2')) +
  geom_bar(position = "stack", stat = "identity") + 
  theme_bw() +
  theme(legend.position = "right",
        axis.text.x = element_text(angle = 45, size = 8, face = "bold", hjust = 1)) +
  ylab("count") + xlab("patient_id") + ggtitle("Relative Cell Types Abundance")  +
  scale_fill_manual(values = c( 'violetred', 'coral1', 'yellow', 'peachpuff', 'thistle', 'lightskyblue1'))
```

```{r, message=FALSE, warning=FALSE}
Idents(Myeloid) <- "Level1Labels_Myeloid"
DefaultAssay(Myeloid) <- "CorrectedCounts"

Myeloid <- ScaleData(Myeloid)
Myeloid <- NormalizeData(Myeloid)

DimPlot(Myeloid, reduction = "umap", label = TRUE, pt.size = 0.03)
```

# Subset Myeloid Cells
```{r, message=FALSE, warning=FALSE}

alt_act_macro <- subset(Myeloid, idents = c("Alternatively Activated Macrophage"))
classical <- subset(Myeloid, idents = c("Classical Macrophage"))
gran <- subset(Myeloid, idents = c("Granulocyte", "Activated Granulocyte"))
```


# Looking at CCR1-CCL5 Signaling
```{r, message=FALSE, warning=FALSE}
Macro <- c("CCR1", "CCR5", "CCR2")
Idents(Myeloid) <- "timepoint"
VlnPlot(Myeloid, features = Macro, pt.size = 0) 
FeaturePlot(Myeloid, features = c("CCR1"), order = TRUE, split.by = "timepoint") 
FeaturePlot(Myeloid, features = c('CCR5'), split.by = "timepoint") & scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdYlBu")))


Macro <- c("CCL7", "CXCR4", "CXCL12", "SPP1")
Idents(Myeloid) <- "timepoint"
VlnPlot(Myeloid, features = Macro, pt.size = 0)

Macro <- c("CCR1", "CCR5")
Idents(alt_act_macro) <- "timepoint"
VlnPlot(alt_act_macro, features = Macro, pt.size = 0, cols = c("pink", "magenta"))
```

# Checking T-Cell Expression 

```{r, message=FALSE, warning=FALSE}
tcell <- readRDS("../OBJECTS/Annotated_longitudinal_T_cell_AH.rds")
Idents(tcell) <- "Level2Labels_T_Cell"
levels(tcell)
VlnPlot(tcell, features = c('CCL5'), pt.size = 0, cols = c('pink', 'magenta'), split.by = "timepoint", split.plot = TRUE)

```