---
title: "06_Myeloid_Cell_Characterization"
author: "Aylin Henstridge (Aylinhen@umich.edu)"
date: "2025-12-09"
output: 
  html_document:
    toc: true
    toc_depth: 2
    warnings: FALSE
    number_sections: true
    toc_float: true
    code_download: true
    fig_caption: true
    fig_width: 10
    fig_height: 6
    highlight: 'tango'
    theme: united
knit: (function(input, ...){rmarkdown::render(input, output_dir = "../DOCUMENTS")})
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(toc = TRUE)
```

```{css, echo = FALSE}
pre {
  max-height: 500px;
  overflow-y: auto;
}

pre[class]{
  max-height: 500px;
}

.scroll-100{
  max-height: 500px;
  overflow-y: auto;
  background-color: inherit;
}
```

# Myeloid Cell Population - Load object and libraries

```{r, warning=FALSE, message=FALSE}
##Myeloid Cells 
suppressPackageStartupMessages({
library(Seurat)
library(monocle3) 
library(pheatmap)
library(tidyverse)
library(RColorBrewer)
library(readxl)
library(DT)
library(fgsea)
library(msigdbr)
library(EnhancedVolcano)
library(enrichplot)
library(cowplot)
library(DESeq2)
library(ggalt)
library(devtools)
library(ashr)
library(tidytree)
library(clusterProfiler)
}) 
source("../UTILS/pseudobulk_functions.R")

myeloid <- readRDS("../OBJECTS/eileen_annotated_longitudibal_myeloid.rds")
```

# Plot full UMAP
```{r, warning=FALSE, message=FALSE}
Idents(myeloid) <- "Level1Labels_Myeloid"
DefaultAssay(myeloid) <- "CorrectedCounts"

myeloid <- ScaleData(myeloid)
myeloid <- NormalizeData(myeloid)

DimPlot(myeloid, reduction = "umap", label = TRUE, pt.size = 0.03)
```

# Subset by cell subtype
```{r, warning=FALSE, message=FALSE}
alt_act_macro <- subset(myeloid, idents = c("Alternatively Activated Macrophage"))
classical <- subset(myeloid, idents = c("Classical Macrophage"))
gran <- subset(myeloid, idents = c("Granulocyte", "Activated Granulocyte"))
```


## Calculate relative freq (fractions) of each cell type
```{r, warning=FALSE, message=FALSE}
DefaultAssay(myeloid) <- "CorrectedCounts"

myeloid$Level1Labels_Myeloid
samples.list <- unique(myeloid$sample_id)
clusters <- lapply(samples.list, function(x){
  subset <- subset(myeloid, subset = sample_id == x)
  dist <- data.frame(table(subset$Level1Labels_Myeloid))
  
  return(dist)
})

names(clusters) <- samples.list

clusters_percent <- lapply(clusters, FUN = function(x){
  summ <- sum(x$Freq)
  x$Freq <- (x$Freq/summ)
  return(x)
})

#making things ggplot-friendly!
clusters_dist <- reshape2::melt(clusters, id.var = "Var1")
colnames(clusters_dist) <- c("Level1Labels_Myeloid","variable","value","sample_id")   
clusters_percent_dist <- reshape2::melt(clusters_percent, id.var = "Var1")
colnames(clusters_percent_dist) <- c("Level1Labels_Myeloid","variable","value","sample_id")

ggplot(clusters_percent_dist, aes(fill=Level1Labels_Myeloid, y = value, x = sample_id)) + 
  geom_bar(position = "stack", stat = "identity") + 
  theme_bw() +
  theme(legend.position = "right",
        axis.text.x = element_text(angle = 45, size = 8, face = "bold", hjust = 1)) + scale_fill_manual(values = c('tan','wheat','darkseagreen1','darkslategray','darkorange','goldenrod3','darkorchid4','darkorange4','lightblue','gold','mediumorchid1','lavender','mediumpurple1','mediumvioletred','midnightblue','limegreen','violetred1'))
```


# Pseudobulk 
```{r, warning=FALSE, message=FALSE}
##################################################################
##                Pseudobulk for each population                ##

myeloid_DGE <- pseudobulk_dge(seurat_object = myeloid, assay = "CorrectedCounts",
                            aggregate_by = "sample_id", comparison = "time_point")
alt_act_macro_DGE <- pseudobulk_dge(seurat_object = alt_act_macro, assay = "CorrectedCounts",
                              aggregate_by = "sample_id", comparison = "time_point")
classical_DGE <- pseudobulk_dge(seurat_object = classical, assay = "CorrectedCounts",
                              aggregate_by = "sample_id", comparison = "time_point")
gran_DGE <- pseudobulk_dge(seurat_object = gran, assay = "CorrectedCounts",
                              aggregate_by = "sample_id", comparison = "time_point")
#################################################################
##                          PCA Plots                          ##
#################################################################
pca_plot(myeloid_DGE, groups = "time_point") + ggtitle("Myeloid Cell Population")
pca_plot(alt_act_macro_DGE, groups = "time_point") + ggtitle("Alternativel Activated Macrophage Cell Population")
pca_plot(classical_DGE, groups = "time_point") + ggtitle("Classical  Macrophage Cell Population")
pca_plot(gran_DGE, groups = "time_point") + ggtitle("Granulocyte Cell Population")
```

# Total Myeloid Analysis
```{r, warning=FALSE, message=FALSE}
Idents(myeloid) <- "Level1Labels_Myeloid"
levels(myeloid)
myeloid <- subset(myeloid, idents = c('Junk'), invert = TRUE)
myeloid <- NormalizeData(myeloid, normalization.method = "LogNormalize", scale.factor = 10000)
myeloid <- FindVariableFeatures(myeloid, selection.method = "vst", nfeatures = 2000, assay = "CorrectedCounts")
myeloid <- ScaleData(myeloid, features = rownames(myeloid),verbose = FALSE)


FeaturePlot(myeloid, features = c('CXCL8'))
```

# Differential Gene Expression of all Myeloid Cells 
```{r, warning=FALSE, message=FALSE}
Idents(object = myeloid) <- 'time_point'
levels(myeloid)
myeloid.MARKERS <- FindMarkers(myeloid, ident.1 = "1", ident.2 = "2", assay = "CorrectedCounts", test.use = "MAST", verbose = FALSE, recorrect_umi = FALSE, logfc.threshold = 0)
#write.csv(myeloid.MARKERS, file = "../DATA_FILES/ITGAMPOSITIVE_MYELOID.markers_de.csv")
```

# Violin Plots
```{r, warning=FALSE, message=FALSE}
Macro <- c("CCR1", "CCR5", "CCR2")
Idents(myeloid) <- "time_point"
VlnPlot(myeloid, features = Macro, pt.size = 0)

Macro <- c("CCR1", "CCR5", "CCR2")
Idents(myeloid) <- "time_point"
VlnPlot(myeloid, features = Macro, pt.size = 0) 
FeaturePlot(myeloid, features = c("CCR1"), order = TRUE, split.by = "time_point") 
FeaturePlot(myeloid, features = c('CCR5'), split.by = "time_point") & scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdYlBu")))

Macro <- c("CCL7", "CXCR4", "CXCL12", "SPP1")
VlnPlot(myeloid, features = Macro, pt.size = 0)

Macro <- c("CCR1", "CCR5")
Idents(alt_act_macro) <- "time_point"
VlnPlot(alt_act_macro, features = Macro, pt.size = 0, cols = c("pink", "magenta"))

```
