---
title: "07_Fibroblast_Cell_Characterization_Part1"
author: "Aylin Henstridge (Aylinhen@umich.edu)"
date: "2025-12-09"
output: 
  html_document:
    toc: true
    toc_depth: 2
    warnings: FALSE
    number_sections: true
    toc_float: true
    code_download: true
    fig_caption: true
    fig_width: 10
    fig_height: 6
    highlight: 'tango'
    theme: united
knit: (function(input, ...){rmarkdown::render(input, output_dir = "../DOCUMENTS")})
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(toc = TRUE)
```

```{css, echo = FALSE}
pre {
  max-height: 500px;
  overflow-y: auto;
}

pre[class]{
  max-height: 500px;
}

.scroll-100{
  max-height: 500px;
  overflow-y: auto;
  background-color: inherit;
}
```

# CAF Cell Population - Load object and libraries

```{r, warning=FALSE, message=FALSE}
##fibroblast signatures

##Aylin henstridge 3/13/2024
suppressPackageStartupMessages({
library(Seurat)
library(SeuratObject)
library(SeuratWrappers)
library(AUCell)
library(monocle3)
library(GSVA)
library(pheatmap)
library(tidyverse)
library(RColorBrewer)
library(DT)
})
#read in subsested object. this object contains the fibroblasts/fibro only epithelial cells for the dataset. 

fibro <- readRDS("../OBJECTS/eileen_annotated_longitudinal_FibroEndo.rds")
Idents(object = fibro) <- "Level1Labels_FibroEndo"

#make an interactive data table to search for genes present in clusters. 
markers <- FindAllMarkers(fibro, assay = "CorrectedCounts", min.pct = 0.25, only.pos = T) 
datatable((markers), filter = 'top', caption = "Seurat Cluster Markers", options = list(scrollX = T))

#change identity to what you want cluster sorted by in UMAP (i.e cluster names here)
DimPlot(fibro, reduction = "umap", label = TRUE, pt.size = 0.03)
```

```{r, warning=FALSE, message=FALSE}
DefaultAssay(fibro) <- "CorrectedCounts"
Idents(fibro) <- "Level1Labels_FibroEndo"
fibro <- subset(fibro, idents = c("Fibro1", "Fibro2"))

DimPlot(fibro, reduction = "umap", label = TRUE, pt.size = 0.03)
```

# RE-CLUSTER SUBSETTED DATA NOW 
```{r, warning=FALSE, message=FALSE}
DefaultAssay(fibro) <- "integrated"
fibro <- FindVariableFeatures(fibro, selection.method = "vst", nfeatures = 2000, assay = "CorrectedCounts")
fibro <- ScaleData(fibro, features = rownames(fibro),verbose = FALSE)

fibro <- RunPCA(fibro, verbose = FALSE)
ElbowPlot(fibro, 50)
PCNUM = 15
fibro <- RunUMAP(fibro, reduction = "pca", dims = 1:PCNUM)
fibro <- FindNeighbors(fibro, reduction = "pca", dims = 1:PCNUM)
fibro <- FindClusters(fibro, resolution = 0.1)
fibro <- readRDS("../OBJECTS/FinalFibroblasts.RDS")
Idents(fibro) <- "UMAP_Clusters"
DimPlot(object = fibro, reduction = "umap", label = FALSE
        , pt.size = 0.5, cols = c("salmon", "chartreuse4", "cornflowerblue"))
```

# Cell_frequency plot
```{r, warning=FALSE, message=FALSE}
Idents(fibro) <- "UMAP_Clusters"
levels(fibro)

fibro$UMAP_Clusters
samples.list <- unique(fibro$sample_id)
clusters <- lapply(samples.list, function(x){
  subset <- subset(fibro, subset = sample_id == x)
  dist <- data.frame(table(subset$UMAP_Clusters))
  
  return(dist)
})

names(clusters) <- samples.list

#calculate relative freq (fractions) of each cell type
clusters_percent <- lapply(clusters, FUN = function(x){
  summ <- sum(x$Freq)
  x$Freq <- (x$Freq/summ)
  return(x)
})

#making things ggplot-friendly!
clusters_dist <- reshape2::melt(clusters, id.var = "Var1")
colnames(clusters_dist) <- c("UMAP_Clusters","variable","value","sample_id")   
clusters_percent_dist <- reshape2::melt(clusters_percent, id.var = "Var1")
colnames(clusters_percent_dist) <- c("UMAP_Clusters","variable","value","sample_id")

ggplot(clusters_percent_dist, aes(fill=UMAP_Clusters, y = value, x = sample_id)) + 
  geom_bar(position = "stack", stat = "identity") + 
  theme_bw() +
  theme(legend.position = "right",
        axis.text.x = element_text(angle = 45, size = 8, face = "bold", hjust = 1)) +
  ylab("count") + xlab("patient_id") + ggtitle("Relative Cell Types Abundance") +
  scale_fill_manual(values = c('salmon', 'chartreuse4', 'cornflowerblue'))
```

# Dotplot of gene expression 
```{r, warning=FALSE, message=FALSE}
genes <- c("PDGFRA", "NEGR1", "SLIT2", "ROBO1", 
           "SEMA3A", "NRP1", "NFIA",
           "EPHA3",
           "ACTA2", "TAGLN", "THY1",
           "COL1A1", "COL1A2",
           "VIM",
           "POSTN", "CXCL12", "DPT")
DotPlot(object = fibro, features = genes, cols = c("white","magenta4"), scale = TRUE) + theme(legend.position= "right", axis.text.x = element_text(angle=45, size=10, hjust=1))
```

# Differentially and Top Expressed Genes
```{r, warning=FALSE, message=FALSE}
fibro.markers <- FindAllMarkers(fibro, only.pos = TRUE, min.pct = 0.25,logfc.threshold = 0.25) #always use 0.25 for percent and fold change threshold
fibro.markers %>% group_by(cluster) %>% top_n(n=2, wt=avg_log2FC) #ranks biggest to smallest
#write.csv(fibro.markers, file = "../DATA_FILES/fibro_markers.csv") #this will create CSV file of clusters and genes                    
```

# AUCELL ANALYSIS ON FIBROBLASTS USING KNOWN GENE SIGNATURES
```{r, warning=FALSE, message=FALSE}
library(readxl)
mycaf_icaf <- read_excel("../GENE_SIGNATURES/MYCAF_ICAF.xlsx")
mycaf <- mycaf_icaf$mycaf
icaf <- mycaf_icaf$icaf
apcaf <- mycaf_icaf$apcaf

mycaf_icaf <- list(
  mycaf = mycaf,
  icaf = icaf,
  apcaf = apcaf
)
expr <- GetAssayData(fibro,
                     assay = "CorrectedCounts",
                     layer = "counts")
geneRanking <- AUCell_buildRankings(expr, nCores = 36, splitByBlocks = TRUE)

auc_score_2 <- AUCell_calcAUC(rankings = geneRanking, geneSets = mycaf_icaf, aucMaxRank = nrow(geneRanking)*0.1)

#make a data frame with ALL of the different types of auc scoring generated with different gene sets
auc_score_2 <- as.data.frame(t(assay(c(auc_score_2))))
auc_score_scaled_2 <- as.data.frame(scale(auc_score_2))
#scaled the data and add it as metadata
fibro <- AddMetaData(fibro, metadata = auc_score_scaled_2)
```

## Create the plot object and display it in the console
```{r, warning=FALSE, message=FALSE}
FeaturePlot(fibro, features = c("mycaf", "icaf", "apcaf"), label = FALSE, repel = TRUE, order = TRUE) & 
  scale_colour_gradientn(scale = TRUE, colours = rev(brewer.pal(n = 11, name = "RdYlBu")))
FeaturePlot(fibro, features = c("icaf"), label = FALSE, repel = TRUE, order = TRUE) & 
  scale_colour_gradientn(scale = TRUE, colours = rev(brewer.pal(n = 11, name = "RdYlBu")))
FeaturePlot(fibro, features = c("apcaf"), label = FALSE, repel = TRUE, order = TRUE) & 
  scale_colour_gradientn(scale = TRUE, colours = rev(brewer.pal(n = 11, name = "RdYlBu")))
```

## Heatmap of AUCELL Scoring
```{r, warning=FALSE, message=FALSE}
tissue_cell_data <- FetchData(fibro, vars = c('mycaf','icaf','sample_id'))
n <- 1 # number of metadata columns
patient_avg <- data.frame()
for (id in levels(factor(tissue_cell_data$sample_id))) {
  data_subset <- tissue_cell_data %>% filter(sample_id == id)
  data_subset_avg <- apply(data_subset[,1:(ncol(data_subset)-n)], 2, mean)
  patient_avg <- rbind(patient_avg, data_subset_avg)
}
colnames(patient_avg) <- colnames(tissue_cell_data)[1:(ncol(tissue_cell_data)-n)]
rownames(patient_avg) <- levels(factor(tissue_cell_data$sample_id))
cycling <- pheatmap(patient_avg, 
                    color = colorRampPalette(c("blue", "white", "red"))(256),  # Color palette
                    main = "Heatmap of Fibroblast Gene Sig.(scale by column)",   # Title of the heatmap
                    clustering_distance_rows = "euclidean",   # Distance metric for row clustering
                    clustering_distance_cols = "euclidean",   # Distance metric for column clustering
                    cellwidth = 10,
                    cellheight = 10,
                    fontsize = 8,           # Font size of row and column labels
                    legend = TRUE,           # Show legend
                    cluster_rows = FALSE,   # Do not cluster rows
                    cluster_cols = TRUE,    # Do not cluster columns
                    width = 100,   # Adjust the width of the plot
                    height = 100,   # Adjust the height of the plot
                    xlab = "signatures",  # X-axis label
                    ylab = "Patient_Timepoint"   # Y-axis labelhttp://127.0.0.1:22419/graphics/9f4d525b-e106-4a69-8ae6-695b611e88a4.png
)
```

```{r, warning=FALSE, message=FALSE}
cycling <- pheatmap(patient_avg, 
                    color = colorRampPalette(c("blue", "white", "red"))(256),  # Color palette
                    main = "Heatmap of Fibroblast Gene Sig. (scale by row)",   # Title of the heatmap
                    clustering_distance_rows = "euclidean",   # Distance metric for row clustering
                    clustering_distance_cols = "euclidean",   # Distance metric for column clustering
                    scale = "row",
                    cellwidth = 10,
                    cellheight = 10,
                    fontsize = 8,           # Font size of row and column labels
                    legend = TRUE,           # Show legend
                    cluster_rows = FALSE,   # Do not cluster rows
                    cluster_cols = TRUE,    # Do not cluster columns
                    width = 100,   # Adjust the width of the plot
                    height = 100,   # Adjust the height of the plot
                    xlab = "signatures",  # X-axis label
                    ylab = "Patient_Timepoint"   # Y-axis labelhttp://127.0.0.1:22419/graphics/9f4d525b-e106-4a69-8ae6-695b611e88a4.png
)
```


## Featureplots of Gene Expression
```{r, warning=FALSE, message=FALSE}
DefaultAssay(fibro) <- "CorrectedCounts"                                                              
FeaturePlot(fibro, features = c("NEGR1","NRP1", "ACTA2", "CXCL12"), pt.size = 1)& scale_color_gradientn(colours =rev(brewer.pal(n=11, name = "RdYlBu"))) & theme(legend.position = "right")  # Ensures the color bar is visible
FeaturePlot(fibro, features = c("NFIA","ROBO1", "SLIT2", "EPHA3"), pt.size = 1) & scale_color_gradientn(colours =rev(brewer.pal(n=11, name = "RdYlBu"))) & theme(legend.position = "right")  # Ensures the color bar is visible
FeaturePlot(fibro, features = c("ROBO1", "CXCL12", "DPT", "LRRC15"), pt.size = 1) & scale_color_gradientn(colours =rev(brewer.pal(n=11, name = "RdYlBu"))) & theme(legend.position = "right")  # Ensures the color bar is visible
```

## Violin Plots 
```{r, warning=FALSE, message=FALSE}
Idents(fibro) <- "patient_id"
VlnPlot(fibro, features = c("NEGR1", "NRP1","NFIA"), pt.size = 0, split.by = "time_point", split.plot = TRUE)
VlnPlot(fibro, features = c("EPHA3", "SLIT2", "DPT"), pt.size = 0, split.by = "time_point", split.plot = TRUE)
VlnPlot(fibro, features = c("ACTA2", "LRRC15", "FAP", "FABP4"), pt.size = 0, split.by = "time_point", split.plot = TRUE)
#VlnPlot(fibro, features = c("SEMA3B"), pt.size = 0, split.by = "time_point", split.plot = TRUE)

#saveRDS(fibro, "../OBJECTS/final_fibroblasts_for_part2.RDS")
#fibro <- readRDS("../OBJECTS/final_fibroblasts_for_part2.RDS")

```