---
title: "09_Merging Normal and Untreated tumor fiborlbasts (Carpenter et al. Cancer Discovery) "
author: "Aylin Henstridge (Aylinhen@umich.edu)"
date: "2025-12-09"
output: 
  html_document:
    toc: true
    toc_depth: 2
    warnings: FALSE
    number_sections: true
    toc_float: true
    code_download: true
    fig_caption: true
    fig_width: 10
    fig_height: 6
    highlight: 'tango'
    theme: united
knit: (function(input, ...){rmarkdown::render(input, output_dir = "../DOCUMENTS")})
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(toc = TRUE)
```

```{css, echo = FALSE}
pre {
  max-height: 500px;
  overflow-y: auto;
}

pre[class]{
  max-height: 500px;
}

.scroll-100{
  max-height: 500px;
  overflow-y: auto;
  background-color: inherit;
}
```

# Load object and libraries
```{r, warning=FALSE, message=FALSE}
suppressPackageStartupMessages({
library(Seurat)
library(SeuratObject)
library(SeuratWrappers)
library(AUCell)
library(monocle3)
library(GSVA)
library(pheatmap)
library(tidyverse)
library(RColorBrewer)
library(DT)
})
```

## Longitudinal dataset fibroblasts from part 7 & 8
```{r, warning=FALSE, message=FALSE}
fibro <- readRDS("../OBJECTS/final_fibroblasts_for_part2.RDS")
Idents(object = fibro) <- "Level1Labels_FibroEndo"
levels(fibro)
Idents(fibro) <- "time_point"
levels(fibro)
T1 <- subset(fibro, idents = c("treatment naive (Timepoint 1)"))
T1$treatment_status <- "treatment naive"
T2 <- subset(fibro, idents = c("post-chemotherapy (Timepoint 2)"))
T2$treatment_status <- "treated"
fibro_labelled <- merge(T1, T2)

Idents(object = fibro_labelled) <- "treatment_status"
levels(fibro_labelled)
fibro_labelled$DiseaseState <- "Tumor"
```

## Published dataset of normal pancreas and treatment naive PDAC
```{r, warning=FALSE, message=FALSE}
GOL <- readRDS("../OBJECTS/gift_of_life_fibros.rds")
Idents(GOL) <- "DiseaseState"
levels(GOL)
GOL$treatment_status <- "treatment naive"
Idents(GOL) <- "cell_types"
GOL <- subset(GOL, idents = c("Fibroblast"))
#saveRDS(GOL, "../OBJECTS/gift_of_life_fibros_noperi.rds")

Idents(GOL) <- "treatment_status"
levels(GOL)
Idents(fibro_labelled) <- "Level1Labels" #removing last pericytes
fibro_labelled <- subset(fibro_labelled, idents = "Fibroblast")
```

# Merge datasets
```{r, warning=FALSE, message=FALSE}
all_fibroblasts <- merge(GOL, fibro_labelled)
Idents(all_fibroblasts) <- "DiseaseState"
levels(all_fibroblasts)
Idents(all_fibroblasts) <- "treatment_status"
levels(all_fibroblasts)
Idents(all_fibroblasts) <- "Level1Labels"
levels(all_fibroblasts)
table(all_fibroblasts$Level1Labels)
table(all_fibroblasts$treatment_status)

#saveRDS(all_fibroblasts, "../OBJECTS/GOL_and_longitduinal_fibroblasts.rds")
#merged dataset saved but not integrated

#all_fibroblasts <- readRDS("../OBJECTS/merged_GOL_LONG_FIBRO_NO_PERI.rds")
```

# Analayze Merged Object
```{r, warning=FALSE, message=FALSE}
DefaultAssay(all_fibroblasts) <- "CorrectedCounts"
Fibro <- NormalizeData(all_fibroblasts)
Fibro <- ScaleData(Fibro)

Idents(Fibro) <- "treatment_status"
library(ggpubr)
trt_naive <- subset(Fibro,idents = c("treatment naive"))
Idents(trt_naive) <- "DiseaseState"
VlnPlot(trt_naive, features = c("NEGR1", "NFIA", "SLIT2", "APP", "EPHA3"), pt.size = 0)
table(trt_naive@meta.data$DiseaseState)
```
# Merging two types of metadata into one to compare a more detailed category
```{r, warning=FALSE, message=FALSE}
Fibro$disease <- paste(Fibro$DiseaseState, Fibro$treatment_status, sep = "_")
```

# Gene Expression 
```{r, warning=FALSE, message=FALSE}
Idents(Fibro) <- "disease"
Fibro2 <- subset(Fibro, idents = c ("AdjNormal_treatment naive"), invert = TRUE)
VlnPlot(Fibro2, features = c("NEGR1", "NFIA"), cols = c("gray", "pink", "magenta"), pt.size = 0)
VlnPlot(Fibro2, features = c("SLIT2", "EPHA3"), cols = c("gray", "pink", "magenta"), pt.size = 0)
VlnPlot(Fibro2, features = c("ACTA2", "NRP1"), cols = c("gray", "pink", "magenta"), pt.size = 0)
length(Cells(Fibro2))
```

# NR-CAF Signature 
```{r, warning=FALSE, message=FALSE}
agf_signature <- c("NEGR1", "SLIT2", "ROBO1", "EPHA3","NRP1", "NFIA")
AGF <- list(
  
  agf_signature = agf_signature
)
expr <- GetAssayData(Fibro2,
                     assay = "CorrectedCounts",
                     layer = "counts")
geneRanking <- AUCell_buildRankings(expr, nCores = 36, splitByBlocks = TRUE)
auc_score <- AUCell_calcAUC(rankings = geneRanking, geneSets = AGF, aucMaxRank = nrow(geneRanking)*0.1)

#make a data frame with ALL of the different types of auc scoring generated with different gene sets
auc_score <- as.data.frame(t(assay(c(auc_score))))
auc_score_scaled <- as.data.frame(scale(auc_score))

#scaled the data and add it as metadata
Fibro2 <- AddMetaData(Fibro2, metadata = auc_score_scaled)

```
# Remove healthy patients & categorize NR+ and NR- CAFs 
```{r, warning=FALSE, message=FALSE}
Idents(Fibro2) <- "DiseaseState"
levels(Fibro2)
Fibro3 <- subset(Fibro2, idents = c("Tumor"))

agf_threshold <- quantile(Fibro3$agf_signature, 0.75)  # top 25%
# 2. Create a new metadata column
Fibro3$agf <- ifelse(Fibro3$agf_signature >= agf_threshold, "agf", "caf")
# Check distribution
ag_caf_cafs <- table(Fibro3$agf, Fibro3$patient_id)
ag_caf_cafs <- as.data.frame(ag_caf_cafs)

library(tidyr)
ag_caf_cafs <- pivot_wider(
  ag_caf_cafs,
  names_from = Var1,
  values_from = `Freq`,   # column with counts
  values_fill = 0           # fill missing with 0 if needed
)
head(ag_caf_cafs)
#write.csv(ag_caf_cafs, "../DATA_FILES/gift_of_life_agcafs_long.csv")

```